name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3" # Updated to your local Flutter version

      - name: Run Flutter Lint
        run: flutter analyze

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3" # Updated to your local Flutter version

      - name: Run Flutter Tests
        run: flutter test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3" # Updated to your local Flutter version

      - name: Build APK
        run: flutter build apk --release

      - name: Build iOS
        run: flutter build ios --release
